steps:
  - name: "gcr.io/trentiemeciel/poetry-builder"
    args: ["export", "--format", "requirements.txt", "--output", "requirements.txt", "--without-hashes"]
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - functions
    - deploy
    - push-arrivals-and-departures
    - --project=trentiemeciel
    - --source=.
    - --region=europe-west3
    - --entry-point=from_pubsub
    - --runtime=python39
    - --memory=128
    - --trigger-topic=push-arrivals-and-departures

    
